In [5]:
import numpy as np 

In [6]:
#Khai báo mảng có 12 phần tử
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [7]:
#Khai báo mảng 2 chiều
matrix = np.array([[1,2,3,4,5,6],
                  [7,8,9,10,11,12]])
print(matrix)
print(matrix.ndim)#Số chiều
print(matrix.shape)#Kích thước(row,col)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
2
(2, 6)


In [8]:
matrix.shape = (3,4)#đổi sang matran 3 dòng 4 cột

In [9]:
arr1 = np.arange(24)

In [10]:
arr1.shape = (2,3,4)
print(arr1)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [11]:
arr1.shape = (2,2,2,3)
print(arr1)

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]


 [[[12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]]]]


In [12]:
x = np.random.randint(20,size=6)
x

array([14, 17,  5, 13,  8,  9])

In [13]:
x1 = np.random.randint(10,size=(3,4))
x1

array([[4, 3, 0, 3],
       [5, 0, 2, 3],
       [8, 1, 3, 3]])

In [14]:
x1[1,2]#access element

2

In [15]:
x1[1,2] = 6
x1

array([[4, 3, 0, 3],
       [5, 0, 6, 3],
       [8, 1, 3, 3]])

In [16]:
#slicing
x[0:3]

array([14, 17,  5])

In [17]:
x[2::2]#Start, stop, step

array([5, 8])

In [18]:
x1[:,:2]

array([[4, 3],
       [5, 0],
       [8, 1]])

<h1>Reshaping of Array and Tranpose</h1>

In [19]:
grid = np.arange(1,10)
grid.shape

(9,)

In [20]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
x = np.array([1,2,3])

In [22]:
x.shape

(3,)

In [23]:
x.reshape((1,3)).shape

(1, 3)

In [24]:
x = np.array([[1.,2.],[3.,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [25]:
x.T
#Tranpose

array([[1., 3.],
       [2., 4.]])

<h1>Array concatenation and splitting</h1>

In [26]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [27]:
np.concatenate((x,y)) 

array([1, 2, 3, 3, 2, 1])

In [28]:
grid = np.array([[1,2,3],[3,2,1]])
grid

array([[1, 2, 3],
       [3, 2, 1]])

In [29]:
np.concatenate((grid,grid))

array([[1, 2, 3],
       [3, 2, 1],
       [1, 2, 3],
       [3, 2, 1]])

In [30]:
np.concatenate((grid,grid),axis =1)

array([[1, 2, 3, 1, 2, 3],
       [3, 2, 1, 3, 2, 1]])

In [31]:
#vstack
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                 [6,5,4]])

In [32]:
np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [33]:
#horizontally stack the arrays: hstack
y = np.array([[99],
              [99]])
np.hstack((y,grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

<h1>Splitting arrays</h1>

In [34]:
x = np.array([1,2,3,99,69,3,2,1])

In [35]:
x1, x2, x3 = np.split(x, [3,5])

In [36]:
x1

array([1, 2, 3])

In [37]:
x2

array([99, 69])

In [38]:
x3

array([3, 2, 1])

<h1>Broadcasting and Vectorized operations</h1>

In [39]:
a = np.arange(3)
a

array([0, 1, 2])

In [40]:
a + 5 #broadcasting

array([5, 6, 7])

In [41]:
b = np.ones([3,3])
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
a.shape, b.shape

((3,), (3, 3))

In [43]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [44]:
a * b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [45]:
c = np.arange(3).reshape(3,1)
c

array([[0],
       [1],
       [2]])

In [46]:
a+c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

<h1>Manipulating and comparing array</h1>

In [47]:
list_number = [1,2,3]
ll = np.array(list_number)
ll

array([1, 2, 3])

In [48]:
sum(ll)#python sum

6

In [49]:
np.sum(ll)#numpy sum

6

In [50]:
#create a massive numpy array
massive_array = np.random.random(10000)
massive_array[:5]
massive_array.shape

(10000,)

In [51]:
%timeit np.sum(massive_array)
#timeit is a funcrtion count time when a cell runing only on jupyter

7.4 µs ± 910 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [52]:
%timeit sum(massive_array)

736 µs ± 39.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [53]:
np.mean(massive_array)

0.5017387179778005

In [54]:
np.max(massive_array)

0.9999709462497284

In [55]:
np.min(massive_array)

2.0027530115096503e-05

<h1>Statistic</h1>
<h>Standard deviation and variance</h>

In [56]:
dog_height = [600,470,170,430,300]
dog_height = np.array(dog_height)
np.std(dog_height)#standard deviation

147.32277488562318

In [57]:
np.var(dog_height)#variance

21704.0

In [58]:
np.sqrt(np.var(dog_height))#phuong sai

147.32277488562318

<h1>Sorting Array</h1>

In [59]:
x = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [60]:
#A related function is argsort, which instead return the indicies of the sorted elements:
np.argsort(x)

array([1, 0, 3, 2, 4], dtype=int64)

<h1>Sorting along row and comlumn</h1>

In [61]:
np.random.seed(42)
MatA = np.random.randint(0,10,size=(4,6))
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [62]:
np.sort(MatA, axis = 0)#sort each column

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [63]:
np.sort(MatA, axis = 1)#sort each row

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

<h1>Linear Algebra</h1>

In [64]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.array([[6,5],
              [4,3],
              [2,1]])

In [65]:
#3x3 dot product 3x2
a.dot(b)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [66]:
#3x2 dot product 3x3
b.T@a

array([[36, 48, 60],
       [24, 33, 42]])

<h1>Dot Product Example</h1>

In [67]:
#Num of jar sold
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [71]:
#create weekly_sales DataFrame
import pandas as pd 
weekly_sales = pd.DataFrame(sales_amounts, index = ["Mon", "Tue", "Wed", "Thu", "Fri"],
                            columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])

weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon             12             15              0
Tue              3              3              7
Wed              9             19             18
Thu              4              6             12
Fri              1              6              7

In [79]:
#create a price array
prices = np.array([10,8,12])
prices.shape #Caution: we should check the shape of array before create a DataFrame

(3,)

In [78]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index = ["Prices"], columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Prices             10              8             12

In [80]:
weekly_sales.shape, butter_prices.shape

((5, 3), (1, 3))

In [88]:
total_prices = weekly_sales.dot(butter_prices.T)
total_prices

Prices
Mon     240
Tue     138
Wed     458
Thu     232
Fri     142

In [89]:
weekly_sales["Total_prices"] = total_prices
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total_prices
Mon             12             15              0           240
Tue              3              3              7           138
Wed              9             19             18           458
Thu              4              6             12           232
Fri              1              6              7           142